WTF-273: linkedIn-runner created
flutterwtf/LinkedIn-Runner pull request #1
Opened 2024-10-30 08:32 UTC by pdubrovskiy

2024-10-30 13:30 UTC, vprudnikoff requested changes

2024-10-30 17:56 UTC, vprudnikoff requested changes

2024-10-30 17:56 UTC, vprudnikoff commented on src/common/errors/validation-error.interface.ts
Это в interfaces должно быть по логике папок.

2024-10-30 17:56 UTC, vprudnikoff commented on src/common/constants/http-status-message.ts
А это вообще нужно? Точто также как и exception filters. У нас же все ошибки в Temporal будут + нет никаких http-ошибок в принципе.

2024-10-30 17:56 UTC, vprudnikoff commented on src/common/interceptors/logging.interceptor.ts
Тоже походу не нужно.

2024-10-30 17:56 UTC, vprudnikoff commented on src/common/middlewares/logger.middleware.ts
Не нужно.

2024-10-30 17:56 UTC, vprudnikoff commented on src/app.module.ts
> +  imports: [LoggerModule, ConfigModule.forRoot(), LinkedInRunnerModule, ScheduleModule.forRoot()],
Предлагаю то, что .forRoot() в начало поставить.

2024-10-30 17:56 UTC, vprudnikoff commented on src/app_modules/linkedin_runner_module/utils/get-last-url-segment.ts
> +export function getLastUrlSegment(url: string): string | undefined {
Давай переименуем get -> extract

2024-10-30 17:56 UTC, vprudnikoff commented on src/app_modules/linkedin_runner_module/constants/connection-request-status.ts
Вроде не нужно.

2024-10-30 17:56 UTC, vprudnikoff commented on src/app_modules/linkedin_runner_module/constants/linkedin-from.ts
Вроде не нужно.

2024-10-30 17:56 UTC, vprudnikoff commented on src/app_modules/linkedin_runner_module/temporal/activities/default-activity.abstract.ts
> +}
Я думаю, что в случае с примитивами, можно обойтись вообще без этого интерфейса, и просто в одном act-методе все делать.

2024-10-31 05:09 UTC, pdubrovskiy commented on src/common/errors/validation-error.interface.ts
почему? это относиться к errors, а внутри папки errors не было смысла делать еще и папку interfaces

2024-10-31 08:07 UTC, LordOfTheVillage requested changes

2024-10-31 08:07 UTC, LordOfTheVillage commented on src/common/utils/hash-object.ts
> +
```
export function hashObject(obj: object): string {
  const jsonString = JSON.stringify(obj);
  return createHash('md5').update(jsonString).digest('hex');
}

```

2024-10-31 13:28 UTC, vprudnikoff requested changes

2024-10-31 13:44 UTC, LordOfTheVillage approved these changes

2024-10-31 16:34 UTC, vprudnikoff approved these changes

2024-10-31 16:34 UTC, merged